# Generated by Django 4.0 on 2021-12-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='emeil',
            new_name='email',
        ),
    ]
