# Generated by Django 4.0 on 2021-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('lsat_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
