# Generated by Django 4.0 on 2021-12-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors_and_movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
    ]
