# Generated by Django 4.0 on 2021-12-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_and_movies', '0003_movie_actor_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(through='actors_and_movies.Actor_movie', to='actors_and_movies.Movie'),
        ),
    ]
