# Generated by Django 4.0 on 2021-12-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors_and_movies', '0004_actor_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='lsat_name',
            new_name='last_name',
        ),
    ]
